import {
  BUSINESS_IMAGE_QUERY_CONFIGS,
  type BusinessImageQueryConfig,
  DEFAULT_IMAGE_QUERIES,
  DEFAULT_REVIEW_QUERIES,
} from "../config/imageQueries.config.js";
import { IMAGE_SLOT_CONFIG } from "../config/imageSlots.config.js";
import {
  IMAGE_QUERY_METADATA_PATTERN,
  IMAGE_SLOTS,
  REQUIRED_IMAGE_QUERY_COUNT,
  type ImageSlot,
} from "./imagePlaceholders.service.js";
import type { AppFormData } from "./landing.types.js";
import {
  normalizeSearchText,
  sanitizeImageQuery,
} from "../utils/text.utils.js";

const REVIEW_SLOT_START_INDEX = 15;

/**
 * Prepares a Gemini image query for Pexels.
 *
 * Gemini already generates a specific query for every image slot,
 * so no additional generic suffixes should be appended.
 *
 * Example:
 * "fresh butter croissant" remains "fresh butter croissant".
 */
const composePexelsQuery = (query: string): string =>
  sanitizeImageQuery(query);

/**
 * Keywords with three or fewer characters are matched only as complete words.
 * This prevents false matches inside longer words.
 */
const matchesKeyword = (
  searchText: string,
  keyword: string,
): boolean => {
  const normalizedKeyword = normalizeSearchText(keyword);

  if (!normalizedKeyword) {
    return false;
  }

  if (normalizedKeyword.length <= 3) {
    return ` ${searchText} `.includes(` ${normalizedKeyword} `);
  }

  return searchText.includes(normalizedKeyword);
};

const getBusinessSearchText = (
  formData: AppFormData,
): string =>
  normalizeSearchText(
    `${formData.ProjectName} ${formData.Description}`,
  );

export const detectConfiguredImageQueryConfig = (
  formData: AppFormData,
): BusinessImageQueryConfig | null => {
  const searchText = getBusinessSearchText(formData);

  return (
    BUSINESS_IMAGE_QUERY_CONFIGS.find(({ keywords }) =>
      keywords.some((keyword) =>
        matchesKeyword(searchText, keyword),
      ),
    ) ?? null
  );
};

const detectConfiguredImageQueries = (
  formData: AppFormData,
): string[] | null => {
  const matchedConfig =
    detectConfiguredImageQueryConfig(formData);

  return matchedConfig
    ? [...matchedConfig.queries]
    : null;
};

/**
 * Extracts the image queries generated by Gemini from HTML metadata.
 */
export const extractGeneratedImageQueries = (
  html: string,
): string[] | null => {
  const match = html.match(IMAGE_QUERY_METADATA_PATTERN);

  if (!match?.[1]) {
    return null;
  }

  try {
    const parsed: unknown = JSON.parse(match[1].trim());

    if (
      !Array.isArray(parsed) ||
      parsed.length < 15 ||
      parsed.length > REQUIRED_IMAGE_QUERY_COUNT ||
      !parsed.every(
        (query) =>
          typeof query === "string" &&
          query.trim().length > 0,
      )
    ) {
      console.warn(
        `Gemini image metadata must contain 15–${REQUIRED_IMAGE_QUERY_COUNT} non-empty strings`,
      );

      return null;
    }

    return parsed.map((query) => query.trim());
  } catch (error) {
    console.warn(
      "Failed to parse Gemini image-query metadata:",
      error,
    );

    return null;
  }
};

/**
 * Completes the query list for every image slot.
 *
 * Gemini queries are passed directly to Pexels after sanitization.
 * Slot suffixes are used only as a last fallback when no other query exists.
 */
const completeImageQueries = (
  queries: readonly string[],
): string[] => {
  return IMAGE_SLOTS.map((slot, index) => {
    const reviewIndex =
      index - REVIEW_SLOT_START_INDEX;

    const rawQuery = queries[index];

    const fallbackQuery =
      DEFAULT_IMAGE_QUERIES[index] ??
      DEFAULT_REVIEW_QUERIES[reviewIndex] ??
      IMAGE_SLOT_CONFIG[slot].querySuffix;

    if (rawQuery?.trim()) {
      const pexelsQuery =
        composePexelsQuery(rawQuery);

      if (pexelsQuery) {
        return pexelsQuery;
      }
    }

    return composePexelsQuery(fallbackQuery);
  });
};

export const resolveImageQueries = (
  formData: AppFormData,
  generatedHtml: string,
): string[] => {
  const generatedQueries =
    extractGeneratedImageQueries(generatedHtml);

  // Queries generated for individual sections have the highest priority.
  if (generatedQueries) {
    return completeImageQueries(generatedQueries);
  }

  const configuredQueries =
    detectConfiguredImageQueries(formData);

  if (configuredQueries) {
    return completeImageQueries(configuredQueries);
  }

  return completeImageQueries(DEFAULT_IMAGE_QUERIES);
};

export const removeImageQueryMetadata = (
  html: string,
): string =>
  html.replace(IMAGE_QUERY_METADATA_PATTERN, "");