export interface BusinessImageQueryConfig {
  id: string;
  keywords: readonly string[];
  queries: readonly string[];
}

export const BUSINESS_IMAGE_QUERY_CONFIGS: readonly BusinessImageQueryConfig[] =
  [
    {
      id: "sushi",
      keywords: [
        "суши",
        "суші",
        "ролл",
        "роли",
        "sushi",
        "japanese food",
        "comida japonesa",
        "cuisine japonaise",
      ],
      queries: [
        "sushi platter japanese restaurant dark table",
        "sushi chef preparing japanese food",
        "japanese restaurant interior",
        "philadelphia sushi roll salmon",
        "california sushi roll",
        "dragon sushi roll",
        "salmon nigiri sushi",
        "sushi set platter",
        "japanese ramen bowl",
        "sushi restaurant interior",
        "sushi chef cooking",
        "fresh salmon sushi",
        "japanese food table",
        "sushi platter close up",
        "japanese restaurant dining",
      ],
    },
    {
      id: "gaming_club",
      keywords: [
        "компьютерный клуб",
        "комп'ютерний клуб",
        "комп’ютерний клуб",
        "пк клуб",
        "кіберклуб",
        "киберклуб",
        "pc club",
        "gaming club",
        "esports",
        "cyber cafe",
        "cibercafe",
        "club gaming",
        "club informatique",
        "salle gaming",
      ],
      queries: [
        "gaming pc club neon computers",
        "esports gaming room computers",
        "gaming club team",
        "gaming pc setup",
        "gaming computer station",
        "vip gaming room",
        "playstation gaming lounge",
        "esports tournament arena",
        "gaming club night neon",
        "gaming club interior",
        "rgb gaming computers",
        "esports players gaming",
        "gaming keyboard mouse",
        "playstation lounge",
        "gaming room neon",
      ],
    },
    {
      id: "coffee_shop",
      keywords: [
        "кофе",
        "кофейня",
        "кава",
        "кав'ярня",
        "кав’ярня",
        "coffee",
        "coffee shop",
        "cafe",
        "cafeteria",
      ],
      queries: [
        "coffee shop cozy interior",
        "barista making coffee",
        "coffee shop team",
        "cappuccino coffee",
        "latte coffee",
        "espresso coffee",
        "croissant pastry",
        "cheesecake dessert",
        "coffee breakfast",
        "coffee shop interior",
        "coffee beans",
        "latte art",
        "cafe dessert",
        "barista coffee machine",
        "friends coffee shop",
      ],
    },
    {
      id: "car_service",
      keywords: [
        "автосервис",
        "автосервіс",
        "ремонт авто",
        "шиномонтаж",
        "car service",
        "auto repair",
        "car repair",
        "taller mecanico",
        "reparacion de coches",
        "service automobile",
        "garage automobile",
        "reparation automobile",
      ],
      queries: [
        "modern auto repair garage",
        "car mechanic workshop",
        "auto service team",
        "car diagnostics mechanic",
        "car oil change",
        "tire service mechanic",
        "car engine repair",
        "car brake repair",
        "car detailing service",
        "auto repair garage",
        "mechanic repairing car",
        "car diagnostic equipment",
        "car workshop tools",
        "tire replacement",
        "car detailing",
      ],
    },
    {
      id: "beauty_salon",
      keywords: [
        "салон красоты",
        "салон краси",
        "маникюр",
        "манікюр",
        "стрижка",
        "перукарня",
        "beauty salon",
        "hair salon",
        "spa",
        "salon de belleza",
        "peluqueria",
        "manicura",
        "salon de beaute",
        "coiffeur",
        "manucure",
      ],
      queries: [
        "luxury beauty salon interior",
        "beauty salon professional",
        "beauty salon team",
        "haircut salon",
        "hair coloring salon",
        "manicure nails salon",
        "facial skincare treatment",
        "spa massage",
        "makeup artist salon",
        "beauty salon interior",
        "hair stylist working",
        "manicure close up",
        "spa treatment",
        "cosmetics salon",
        "beauty client salon",
      ],
    },
  ];

/** English fallback set for business types that are not in the dictionary yet. */
export const DEFAULT_IMAGE_QUERIES: readonly string[] = [
  "modern small business exterior",
  "professional business interior",
  "small business team",
  "professional service detail",
  "modern business product",
  "customer service professional",
  "small business workspace",
  "professional team working",
  "modern commercial interior",
  "business lifestyle",
  "professional workspace",
  "happy customer experience",
  "business product close up",
  "modern company office",
  "small business owner",
];

export const DEFAULT_REVIEW_QUERIES: readonly string[] = [
  "smiling young woman natural customer portrait neutral background",
  "smiling young man natural customer portrait neutral background",
  "smiling mature woman natural customer portrait neutral background",
];